# Generated by Django 6.0.1 on 2026-02-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('back_preview', models.ImageField(blank=True, null=True, upload_to='decks/back/preview/')),
                ('back_full', models.ImageField(blank=True, null=True, upload_to='decks/back/full/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('image_preview', models.ImageField(upload_to='cards/preview/')),
                ('image_full', models.ImageField(upload_to='cards/full/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.deck')),
            ],
            options={
                'ordering': ['deck', 'position', 'id'],
                'indexes': [models.Index(fields=['deck', 'is_active'], name='cards_card_deck_id_4b2778_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('deck', 'code'), name='unique_card_code_in_deck')],
            },
        ),
    ]
