# Generated by Django 6.0.1 on 2026-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='art_original',
            field=models.ImageField(blank=True, null=True, upload_to='cards/art/original/'),
        ),
        migrations.AddField(
            model_name='deck',
            name='frame_color',
            field=models.CharField(default='#2C3A4A', max_length=7),
        ),
        migrations.AddField(
            model_name='deck',
            name='frame_overlay',
            field=models.ImageField(blank=True, null=True, upload_to='decks/frame_overlay/'),
        ),
        migrations.AddField(
            model_name='deck',
            name='text_color',
            field=models.CharField(default='#E8E8E8', max_length=7),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_full',
            field=models.ImageField(blank=True, null=True, upload_to='cards/render/full/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='cards/render/preview/'),
        ),
    ]
