# Generated by Django 6.0.1 on 2026-02-03 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('random_one', '1 random card'), ('pick_one_of_six', 'Pick 1 of 6'), ('past_present_future', 'Past-Present-Future (3)'), ('resource_block_action', 'Resource-Block-Action (3)'), ('emotion_plus_card', 'Emotion + Card'), ('blind_choice', 'Blind choice')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cards.deck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('draw', 'draw'), ('pick', 'pick'), ('flip', 'flip'), ('reset', 'reset')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cards', models.ManyToManyField(blank=True, to='cards.card')),
                ('chosen_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.card')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='session.session')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='session_ses_session_110e7e_idx'), models.Index(fields=['session', 'event_type'], name='session_ses_session_779f84_idx')],
            },
        ),
    ]
