# Generated by Django 6.0.1 on 2026-02-04 17:45

import session.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client_key',
            field=models.CharField(default=session.models.generate_token, editable=False, max_length=64),
        ),
    ]
